  version: "3.8"

  services:
    app:
      build: .
      container_name: my_ratelimiter_app
      ports:
        - "3009:3009"
      depends_on:
        - redis
        - rabbitmq
      environment:
        - REDIS_HOST=redis
        - REDIS_PORT=6379 
        - RABBITMQ_URL=amqp://rabbitmq:5672
      networks:
        - app_network

    redis:
      image: redis:latest
      container_name: redis_server
      restart: always
      ports:
        - "6379:6379"
      networks:
        - app_network

    rabbitmq:
      image: rabbitmq:3-management  
      container_name: rabbitmq_queue
      ports:
        - "5672:5672"
      networks:
        - app_network

  networks:
    app_network:
      driver: bridge
